### PR TITLE
added hyperlinks to bottom nav btns

### PR DESCRIPTION
**Pull request by shubhamKumar1608**

### CODE REVIEW

**Review by priyanshukumarsinha — APPROVED** [review]
very nice

**Comment by priyanshukumarsinha** [comment]
good work @ShubhamKumar-s-k 
Keep it up

**Comment by priyanshukumarsinha** [comment]
good work @ShubhamKumar-s-k 
Keep it up buddy!

**Comment by shubhamKumar1608** [comment]
Thank you @PriyanshuKumarSinha

**Pull request merged**
